# Generated by Django 5.2.3 on 2025-06-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'سهل'), (2, 'متوسط'), (3, 'صعب')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.skillcategory')),
            ],
        ),
    ]
