# Generated by Django 5.2.3 on 2025-06-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_skill_category_alter_skill_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text_choice', 'اختيارات نصية'), ('image_choice', 'اختيارات صور'), ('drag_and_drop', 'سحب وإفلات'), ('audio_input', 'إدخال صوتي')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('options', models.JSONField(help_text='قائمة الاختيارات، يمكن أن تكون نصوصًا أو روابط صور')),
                ('correct_answer', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.skill')),
            ],
        ),
    ]
