# Generated by Django 5.2.3 on 2025-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'سهل'), (2, 'متوسط'), (3, 'صعب')], default=1),
        ),
    ]
