# Generated by Django 5.2.3 on 2025-06-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_remove_skill_level_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
