# Generated by Django 5.2.3 on 2025-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_question_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
