# Generated by Django 5.2.5 on 2025-09-01 00:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_assessmentsession_questionanswer_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_full_name', models.CharField(blank=True, max_length=255)),
                ('child_age_years', models.PositiveIntegerField(blank=True, null=True)),
                ('child_sex', models.CharField(blank=True, max_length=10)),
                ('residence', models.CharField(blank=True, max_length=255)),
                ('child_diagnosis', models.CharField(blank=True, max_length=255)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scq_submissions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_scq', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
