# Generated by Django 5.2.5 on 2025-08-31 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='ولي الأمر لهذا الطفل (اختياري مؤقتًا)', limit_choices_to={'user_type': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialist',
            field=models.ForeignKey(blank=True, help_text='الأخصائي لهذا الطفل (اختياري مؤقتًا)', limit_choices_to={'user_type': 'specialist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
